<?php
/**
 * @author Azaleasoft Team
 * @copyright Copyright (c) 2017 Azaleasoft (http://www.azaleasoft.com)
 * @package Azaleasoft_Asaddressvalidation
 */
?>
<div id="address-suggest"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "asAddressValidationMultishipping": <?php echo $this->helper("Azaleasoft\Asaddressvalidation\Helper\Data")->getMultishippingInitData(); ?>
        }
    }
</script>