<?php
/**
 * @author Azaleasoft Team
 * @copyright Copyright (c) 2017 Azaleasoft (https://www.azaleasoft.com)
 * @package Azaleasoft_Asaddressvalidation
 */
?>
<div id="address-suggest"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "asAdderssValidationCheckout": <?php echo $this->helper("Azaleasoft\Asaddressvalidation\Helper\Data")->getCheckoutInitData(); ?>
        }
    }
</script>
