<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Product Reviews Base for Magento 2
 */
/** @var \Amasty\AdvancedReview\Block\Helpful $block */
// phpcs:ignoreFile
?>
<div class="amreview-helpful-wrap" id="review-helpful-<?= /* @noEscape */ $block->getReview()->getId();?>">
    <input name="form_key" type="hidden" value="<?= /* @noEscape */ $block->getFormKey(); ?>" />
    <span class="amreview-helpful">
        <?= $block->escapeHtml(__('Was this review helpful?'));?>
    </span>
    <div class="amreview-options">
        <button class="amreview-plus" title="<?= $block->escapeHtml(__('Yes, review was helpful.'));?>">
            <span class="amreview-icon"></span>
            <span class="amreview-count">0</span>
        </button>
        <button class="amreview-minus" title="<?= $block->escapeHtml(__('No, review was not helpful.'));?>">
            <span class="amreview-icon"></span>
            <span class="amreview-count">0</span>
        </button>
    </div>
</div>
<script>
    require([
        "jquery",
        "Amasty_AdvancedReview/js/amVote"
    ], function ($) {
        $("#review-helpful-<?= /* @noEscape */ $block->getReview()->getId();?>").amVote(<?= /* @noEscape */ $block->getJsonConfig();?>);
    });
</script>
