<?php
/**
 * @author      Olegnax
 * @package     Olegnax_InstagramFeedPro
 * @copyright   Copyright (c) 2024 Olegnax (http://olegnax.com/). All rights reserved.
 * @noinspection PhpDeprecationInspection
 */
declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Olegnax\InstagramFeedPro\Model\HotSpot;
use Olegnax\InstagramFeedPro\Model\Config\Source\HotspotMobile;
use Olegnax\InstagramFeedPro\Model\Config\Source\MarkerStyle;
use Olegnax\InstagramFeedPro\Model\Config\Source\HotspotIcon;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HotSpot $hotspot */
$hotspot = $block->getHotSpot();
/** @var Product $product */
$product = $hotspot->getProduct();
$hsId = $hotspot->getUniqId();

$mobileBreakpoint = 768;
$mobileBreakpointS = 639;
$inlineStyles = $inlineStylesInner = $customStyles = $classes = $tooltipStyles = [];
$hotspotWidth = (int)$escaper->escapeHtmlAttr($hotspot->getHotspotWidth());
$hotspotHeight = (int)$escaper->escapeHtmlAttr($hotspot->getHotspotHeight());
$hs_text = $escaper->escapeHtml($hotspot->getHotSpotData('hotspot_text'));
$hs_text_fontsize = (int)$escaper->escapeHtml($hotspot->getHotspotTextFontsize());
$hs_text_fontweight = (int)$escaper->escapeHtml($hotspot->getHotspotTextFontweight());
$hs_text_letterspacing = $escaper->escapeHtml($hotspot->getHotspotTextLetterspacing());
$hs_color = $hotspot->getHotspotColor();
$hs_shadow_color = $hotspot->getHotSpotData('hotspot_shadow_color');
$hs_shadow = $hotspot->getHotSpotData('hotspot_shadow');
$hs_bg = $hotspot->getHotspotBg();
$hs_mobile = $hotspot->getHotSpotData('hotspot_mobile');
$tooltipContent = '';
$markerStyle = $hotspot->getHotSpotData('marker_style');
if(!empty($hotspot->getContent())) {
	$tooltipContent = $hotspot->getContentEncoded();
} elseif( $product ){
	$tooltipContent = $product->getName();
}
$iconColor = $hotspot->getHotSpotData('hotspot_color');
$iconStyle = ($hs_color != '') ? ('style="color: ' . $hs_color . '"') : '';
$icon =  $hotspot->getHotSpotData('hotspot_text_icon');
$customIcon = '';
$hs_text_styles = '';
$classes[] = 'ox-ihs__item';

if($hs_text && ($hs_text_fontsize != '' || $hs_text_fontweight != '' || $hs_text_letterspacing != '' || $hs_color != '')){
	if( $hs_text_fontsize && $hs_text_fontsize !='' ){
		$hs_text_styles .='font-size: ' . $hs_text_fontsize . 'px;';
	}
	if( $hs_text_fontweight && $hs_text_fontweight !='' ){
		$hs_text_styles .='font-weight: ' . $hs_text_fontweight . ';';
	}
	if( $hs_text_letterspacing && $hs_text_letterspacing !='' ){
		$hs_text_styles .='letter-spacing: ' . $hs_text_letterspacing . 'px;';
	}
	if( $hs_color && $hs_color != '' ){
		$hs_text_styles .='color: ' . $hs_color . ';';
	}
}
	if($hs_shadow && $hs_shadow_color){
		if($markerStyle == MarkerStyle::TYPE_TAG_HS || $markerStyle == MarkerStyle::TYPE_TAG_HT || $markerStyle == MarkerStyle::TYPE_TAG45 || $markerStyle == MarkerStyle::TYPE_BAG_F){
			$customStyles[] = '#' . $hsId . '.ox-ihs__item.-shadow .-icon-wrap{filter: drop-shadow(0px 5px 9px ' . $hs_shadow_color . ');}';
		} else{
			$inlineStylesInner[] = 'box-shadow: 0px 5px 9px ' . $hs_shadow_color . ';';
		}
	}
	if($markerStyle == MarkerStyle::TYPE_DEFAULT){
		if($hs_bg){
			$inlineStylesInner[] =  'background-color: ' . $hs_bg . ';';
		}
		if($hotspot->getHotspotRadius() != ''){
			$inlineStylesInner[] = 'border-radius: ' . (int)$escaper->escapeHtmlAttr($hotspot->getHotspotRadius()) . 'px;';
		}
		if($hotspotHeight){
			$inlineStyles[] = 'height: ' . $hotspotHeight . 'px;';
		}
		if($hotspotWidth){
			$inlineStyles[] = 'min-width: ' . $hotspotWidth . 'px;';
		}
	}
	if($markerStyle == MarkerStyle::TYPE_BAG_C || $markerStyle == MarkerStyle::TYPE_CART_C){
		if($hs_bg){
			$inlineStylesInner[] =  'background-color: ' . $hs_bg . ';';
		}
	}
	if( $markerStyle == MarkerStyle::TYPE_TAG_HT || $markerStyle == MarkerStyle::TYPE_TAG_HS){
		if($hs_bg){
			$customStyles[] =  '#' . $hsId . '.ox-ihs__item .-icon-inner {background-color: ' . $hs_bg . '!important;}';
		}
	}
	if($markerStyle == MarkerStyle::TYPE_TAG45 || $markerStyle == MarkerStyle::TYPE_TAG_HT || $markerStyle == MarkerStyle::TYPE_TAG_HS){
		if($hotspotHeight){
			$customStyles[] = '#' . $hsId . '.ox-ihs__item .-icon-wrap { height: ' . $hotspotHeight . 'px;}';
		}
		if($hotspotWidth){
			$customStyles[] = '#' . $hsId . '.ox-ihs__item .-icon-wrap { width: ' . $hotspotWidth . 'px;}';
		}
	}
	if($hs_mobile == HotspotMobile::TYPE_HIDE){
		$classes[] = 'hide-on-mobile';
	}
	if($hs_mobile == HotspotMobile::TYPE_MIN){
		$classes[] = 'mobile-minimized';
		$customStyles[] =  '@media only screen and (max-width: ' . $mobileBreakpointS . 'px){#' . $hsId . '.ox-ihs__item.mobile-minimized .inner{background-color: ' . ($hs_bg ?: 'white') . '!important;}}';
	}
	if($hs_shadow){
		$classes[] = '-shadow';
	}
	if(($markerStyle == MarkerStyle::TYPE_TAG_HS || $markerStyle == MarkerStyle::TYPE_TAG_HT || $markerStyle == MarkerStyle::TYPE_TAG45 || $markerStyle == MarkerStyle::TYPE_BAG_F) && $hs_shadow && $hs_mobile == HotspotMobile::TYPE_MIN){
		$customStyles[] =  '@media only screen and (max-width: ' . $mobileBreakpointS . 'px){#' . $hsId . '.ox-ihs__item.-shadow .inner{box-shadow: 0px 5px 9px ' . ($hs_shadow_color ?: 'rgba(0,0,0,0.25)') . '}}';
	}
	if($hotspot->getHotSpotData('hotspot_pulse')){
		$classes[] = '-pulse';
		if($hotspot->getHotspotPulseColor()){
			$customStyles[] = '#' . $hsId . '.ox-ihs__item.-pulse:before{background-color:' . $hotspot->getHotspotPulseColor() . '!important}';
		}
	}
	$classes[] = '-style-' . $markerStyle;
	$classes[] = $escaper->escapeHtmlAttr($hotspot->getHotspotCustomClass());
	
	$tooltip_color = $hotspot->getTooltipTextColor();
	$tooltip_color_background = $hotspot->getTooltipBgColor();
	$tooltip_width = (int)$escaper->escapeHtmlAttr($hotspot->getTooltipWidth());
	$tooltip_border_radius = (int)$escaper->escapeHtmlAttr($hotspot->getTooltipBorderRadius());
	$tooltip_shadow_color = $hotspot->getTooltipShadowColor();
	if(	$hotspotWidth ){
		$tooltipStyles[] = 'left: ' . $hotspotWidth/2 . 'px;';
	}
	if($tooltip_width){
		$tooltipStyles[] = 'width: ' . $tooltip_width . 'px;';
	}
	if($tooltip_color_background != ''){
		$tooltipStyles[] = 'background-color: ' . $tooltip_color_background . ';';
	}
	if($tooltip_color != ''){
		$tooltipStyles[] = 'color: ' . $tooltip_color . ';';
	}
	if($tooltip_border_radius != ''){
		$tooltipStyles[] = 'border-radius: ' . $tooltip_border_radius . 'px;';
	}
	if($tooltip_shadow_color != ''){
		$tooltipStyles[] = 'box-shadow: 0px 4px 20px 0px ' . $tooltip_shadow_color . ';';
	}


	$mainStyles = $hotspot->getStyle();
	if ( !empty($inlineStyles) ){ 
		$mainStyles .= implode(' ', $inlineStyles);
	}
	if ((bool)$mainStyles){
		$customStyles[] = '#' . $hsId . '.ox-ihs__item{' . $mainStyles . '}';
	}

	if (!empty($tooltipStyles) ){ 
		$customStyles[] = '#' . $hsId . '.ox-ihs__item .ox-hotspot__tooltip{' . implode('', $tooltipStyles) . '}';
	}
	if (!empty($inlineStylesInner) ){ 
		$customStyles[] = '#' . $hsId . '.ox-ihs__item .inner{' . implode('', $inlineStylesInner) . '}';
	}
	if ((bool)$hs_text_styles){ 
		$customStyles[] = '#' . $hsId . '.ox-ihs__item .hs-text{' . $hs_text_styles . '}';
	}

	if ( !empty($customStyles) ){
		if (isset($secureRenderer)){
			echo /* @noEscape */ $secureRenderer->renderTag('style', [], implode(' ', $customStyles) , false);
		} else {
			echo '<style>' . implode(' ', $customStyles) . '</style>'; 
		}
	}
?>

<div id="<?= $hsId ?>" class="<?php if ( !empty($classes) ){ echo implode(' ', $classes); } ?>" 
<?= $hotspot->getHtmlAttributes() ?>>
	<div class="inner">
		<?php if ($markerStyle == MarkerStyle::TYPE_TAG45) : ?>
			<div class="-icon-wrap">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28.9 29"><path d="M26,0H16.1A3,3,0,0,0,14,.9L0.8,14.2A2.7,2.7,0,0,0,.9,18l0.2,0.2L10.9,28a2.8,2.8,0,0,0,4,.3L28.1,15a3,3,0,0,0,.9-2.1V3A3,3,0,0,0,26,0ZM21.8,10.5a3,3,0,1,1,3-3A3,3,0,0,1,21.8,10.5Z" transform="translate(-0.1 0)" style="fill:<?= $iconColor ?: '#fff' ?>"/></svg>
			</div>
		<?php elseif ($markerStyle == MarkerStyle::TYPE_TAG_HS) : ?>
			<div class="-icon-wrap">
				<span class="-icon-inner">
					<?php if ( $hs_text != '' ){ ?>
						<span class="hs-text"><?= $hs_text ?></span>
					<?php } ?>
				</span>
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 23 28"><path d="M16,0H0V28H16a7,7,0,0,0,7-7V7A7,7,0,0,0,16,0ZM11,18a4,4,0,1,1,4-4A4,4,0,0,1,11,18Z" style="fill:<?= $hs_bg ?: '#fff' ?>"/></svg>
			</div>
		<?php elseif ($markerStyle == MarkerStyle::TYPE_TAG_HT) : ?>
			<div class="-icon-wrap">
				<span class="-icon-inner">
					<?php if ( $hs_text != '' ){ ?>
						<span class="hs-text"><?= $hs_text ?></span>
					<?php } ?>	
				</span>
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22.9 28"><path d="M20.8,9.2L12.9,1.8A6.6,6.6,0,0,0,8.4,0H0V28H8.4a6.6,6.6,0,0,0,4.5-1.8l7.9-7.4A6.6,6.6,0,0,0,20.8,9.2ZM8,18a4,4,0,1,1,4-4A4,4,0,0,1,8,18Z" style="fill:<?= $hs_bg ?: '#fff' ?>"/></svg>
			</div>
		<?php elseif ($markerStyle == MarkerStyle::TYPE_BAG_F) : ?>
			<div class="-icon-wrap">
				<svg xmlns="http://www.w3.org/2000/svg" width="<?= $hotspotWidth ?: '16' ?>" height="<?= $hotspotHeight ?: '21' ?>" viewBox="0 0 16 21"><path d="M8,2A3,3,0,1,1,5,5,3,3,0,0,1,8,2M8,0a5,5,0,1,0,5,5A5,5,0,0,0,8,0H8Z" style="fill:<?= $iconColor ?: '#fff' ?>"/><rect y="5" width="16" height="16" rx="2" ry="2" style="fill:<?= $iconColor ?: '#fff' ?>"/></svg>
			</div>
		<?php elseif ($markerStyle == MarkerStyle::TYPE_BAG_C) : ?>
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="18" viewBox="0 0 16 18"><path d="M8,2a2,2,0,0,1,2,2V8h2V4A4,4,0,0,0,8,0H8A4,4,0,0,0,4,4V8H6V4A2,2,0,0,1,8,2" style="fill:<?= $iconColor ?: '#000' ?>"/><path d="M14,6V16H2V6H14m0-2H2A2,2,0,0,0,0,6V16a2,2,0,0,0,2,2H14a2,2,0,0,0,2-2V6a2,2,0,0,0-2-2h0Z" style="fill:<?= $iconColor ?: '#000' ?>"/></svg>
		<?php elseif ($markerStyle == MarkerStyle::TYPE_CART_C) : ?>
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M16,0H12.7L12,3H0l2,9H12L14.2,2H16V0ZM10.4,10H3.6L2.5,5h9Z" style="fill:<?= $iconColor ?: '#000' ?>"/><circle cx="3.5" cy="14.5" r="1.5" style="fill:<?= $iconColor ?: '#000' ?>"/><circle cx="10.5" cy="14.5" r="1.5" style="fill:<?= $iconColor ?: '#000' ?>"/></svg>
		<?php elseif ($markerStyle == MarkerStyle::TYPE_DEFAULT) :  ?>
			<?php if ( $icon == HotspotIcon::TYPE_SMALL_PLUS ): ?>
				<span aria-label="<?= $block->escapeHtml(__('Hotspot Icon')) ?>" class="ox-hotspot__icon ox-icon-plus-small" <?= $iconStyle ?>></span>
			<?php elseif ( $icon == HotspotIcon::TYPE_BAG ): ?>
				<svg class="ox-hotspot__icon" xmlns="http://www.w3.org/2000/svg" width="16" height="18" viewBox="0 0 16 18"><path d="M8,2a2,2,0,0,1,2,2V8h2V4A4,4,0,0,0,8,0H8A4,4,0,0,0,4,4V8H6V4A2,2,0,0,1,8,2" style="fill:<?= $iconColor ?: '#000' ?>"/><path d="M14,6V16H2V6H14m0-2H2A2,2,0,0,0,0,6V16a2,2,0,0,0,2,2H14a2,2,0,0,0,2-2V6a2,2,0,0,0-2-2h0Z" style="fill:<?= $iconColor ?: '#000' ?>"/></svg>
			<?php elseif ( $icon == HotspotIcon::TYPE_CART ): ?>
				<svg class="ox-hotspot__icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path d="M16,0H12.7L12,3H0l2,9H12L14.2,2H16V0ZM10.4,10H3.6L2.5,5h9Z" style="fill:<?= $iconColor ?: '#000' ?>"/><circle cx="3.5" cy="14.5" r="1.5" style="fill:<?= $iconColor ?: '#000' ?>"/><circle cx="10.5" cy="14.5" r="1.5" style="fill:<?= $iconColor ?: '#000' ?>"/></svg>
			<?php elseif ( $icon == HotspotIcon::TYPE_CUSTOM ): ?>
				<img src="<?= $customIcon ?>" alt="<?= $block->escapeHtml(__('Hotspot Icon')) ?>" class="ox-hotspot__icon-custom">
			<?php endif; ?>
			<?php if ( $hs_text != '' ){ ?>
				<span class="hs-text"><?= $hs_text ?></span>
			<?php } ?>	
		<?php endif; ?>	
		<?php if($tooltipContent) { ?>
		<div class="ox-hotspot__tooltip">
			<?= $tooltipContent ?>
		</div>
		<?php } ?>
	</div>
</div>
<?php
unset($classes,$customStyles, $inlineStylesInner, $tooltipStyles);
