<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Out of Stock Notification for Magento 2
 */
/** @var Magento\Backend\Block\Template $block */
?>

<?= $block->getChildHtml('before.chart_stock') ?>
<?= $block->getChildHtml('chart_stock') ?>
<div class="amxnotif-table-wrap">
    <?= $block->getChildHtml('wanted_products') ?>
    <?= $block->getChildHtml('last_activity') ?>
</div>
