<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog category image template
 *
 * @var $block \Magefan\BlogPlus\Block\Category\Image
 */
?>
<?php if ($imageUrl = $block->getImageUrl()) { ?>
    <div class="blog-top-image blog-category-top-image">
        <img src="<?= $block->escapeHtml($imageUrl)?>"
             alt="<?= $block->escapeHtml($block->getImageAlt())?>"
             width="<?= $block->getImageWidth() ?>"
             height="<?= $block->getImageHeight() ?>"
        />
    </div>
<?php } ?>