<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Out of Stock Notification for Magento 2
 */
/** @var \Amasty\Xnotif\Block\Catalog\Category\Config $block */
?>
<script type="text/x-magento-init">
{
    "body": {
        "Amasty_Xnotif/js/category_subscribe": {
            "usePopup": "<?= /* @noEscape */ $block->usePopupForSubscribe() ?>",
            "popup": []
        }
    }
}
</script>

<?php if ($block->isConfigurableJsNeeded()): ?>
<script type="text/x-magento-init">
{
    "*": {
        "Amasty_Xnotif/js/category/configurable": <?= /* @noEscape */ $block->getConfigurableInfo() ?>
    }
}
</script>
<?php endif; ?>
